backend:
  name: git-gateway
  branch: main # Branch to update (optional)

media_folder: 'src/assets/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '../../assets/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'articles' # Used in routes, e.g., /admin/collections/blog
    label: 'Novinky' # Used in the UI
    folder: 'src/content/articles' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Nadpis', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Obrázek', name: 'image', widget: 'image', required: false }
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Služby'
    folder: 'src/content/services'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Nadpis', name: 'title', widget: 'string' }
      - { label: 'Hlavní obsah', name: 'body', widget: 'markdown' }
      - { label: 'Cena od', name: 'price', widget: 'string' }
      - {
          label: 'Věk',
          name: 'age',
          widget: 'select',
          options: ['0-2 roky', '1-5 let', '3-5 let', '6+ let', 'každý věk'],
        }
      - {
          label: Doporučené,
          name: 'isFeatured',
          widget: boolean,
          default: false,
        }
      - {
          label: 'Počet dětí',
          name: 'childrenCount',
          widget: 'select',
          options:
            ['jednotlivec', 'do 5 dětí', '6-10 dětí', '11-30 dětí', '30+ dětí'],
        }
      - {
          label: 'Tag',
          name: 'tag',
          widget: 'select',
          options: ['hudba', 'vyrábění', 'tanec', 'divadlo', 'myšák očko'],
          required: false,
        }
      - {
          label: 'Hlavní obrázek',
          name: 'heroImage',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Popis hlavního obrázku',
          name: 'heroImageAlt',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Spodní obsah',
          name: 'bottomContent',
          widget: 'markdown',
          required: false,
        }
      - {
          label: 'Video',
          name: 'videos',
          widget: 'list',
          summary: 'Video',
          field: { label: YouTube ID, name: video, widget: string },
          required: false,
        }
      - {
          label: 'Galerie',
          name: 'images',
          widget: 'list',
          summary: 'Obrázky',
          field: { label: Obrázek, name: image, widget: image },
          required: false,
        }
  - name: 'testimonials' # Used in routes, e.g., /admin/collections/blog
    label: 'Reference' # Used in the UI
    folder: 'src/content/testimonials' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Jméno', name: 'title', widget: 'string' }
      - {
          label: 'Zaměstnání',
          name: 'occupation',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Věk',
          name: 'age',
          widget: 'number',
          value_type: 'int',
          min: 1,
          max: 120,
          required: false,
        }
      - { label: 'Datum', name: 'date', widget: 'datetime', required: false }
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
