backend:
  name: git-gateway
  branch: main # Branch to update (optional)

media_folder: 'public/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'articles' # Used in routes, e.g., /admin/collections/blog
    label: 'Novinky' # Used in the UI
    folder: 'src/content/articles' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Nadpis', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Obrázek', name: 'image', widget: 'image', required: false }
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
  - name: 'services'
    label: 'Služby'
    folder: 'src/content/services'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Nadpis', name: 'title', widget: 'string' }
      - { label: 'Obsah', name: 'body', widget: 'markdown' }
      # - { label: 'Datum', name: 'date', widget: 'datetime' }
      # - { label: 'Obrázek', name: 'image', widget: 'image' }
